# Generated by Django 5.2 on 2025-04-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='scheduled_at',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('online', 'Online'), ('personal', 'Personal')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.service'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('CHANGED', 'Changed')], default='CONFIRMED', max_length=10),
        ),
    ]
