# Generated by Django 5.2 on 2025-04-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_sessions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.service'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('CHANGED', 'Changed')], default='CONFIRMED', max_length=10),
        ),
    ]
