# Generated by Django 5.2 on 2025-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_google_refresh_token'),
        ('viewer', '0009_session_meeting_address_session_meeting_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CANCELLED', 'CONFIRMED', 'CHANGED', 'PENDING'])), name='valid_session_status'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CONFIRMED', 'PENDING'])), fields=('coach', 'date_time'), name='unique_coach_time_slot'),
        ),
    ]
