# Generated by Django 5.2 on 2025-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Name'),
        ),
    ] 