# Generated by Django 5.2 on 2025-05-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
