# Generated by Django 5.2 on 2025-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_google_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hypnotherapy_consent',
            field=models.BooleanField(default=False),
        ),
    ]
