# Generated by Django 5.2 on 2025-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_preferred_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('medical_referral', 'Medical Referral'), ('relative', 'Relative'), ('friend', 'Friend'), ('newspaper', 'Newspaper'), ('radio', 'Radio'), ('television', 'Television'), ('other', 'Other (please specify)')], max_length=50, null=True),
        ),
    ]
