# Generated by Django 5.2 on 2025-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.TextField(blank=True, null=True, verbose_name='Specialization'),
        ),
    ]
