# Generated by Django 5.2 on 2025-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hypnotherapy_consent',
            field=models.BooleanField(default=False),
        ),
    ]
